[package]
name = "trabajo-fin-de-grado"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.6.6", features = ["cors", "fs"] }
